services:
  # Backend service (development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: addis-majlis-backend-dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: npm run start:dev

  # Frontend service (development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: addis-majlis-frontend-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - backend
    networks:
      - app-network
    command: npm run dev -- --host

networks:
  app-network:
    driver: bridge
